### ISSUE TITLE
Not getting plans.xml.gz file in every iteration.

### ISSUE THREAD

**Issue by BarshaLamichhane** [Janekdererste/matsim-example-project-2022#1]
I have cloned and run the matsim-example-project repository but when I run up to the 10th iteration, I can see trips.xml and plans.xml files in output iteration files in iteration 0.  For iteration 1, I can see plans.xml not trips.xml file. From Iteration 2, I can't see both plans.xml.gz and trips.csv.gz. As per my understanding for every iteration, the score function is calculated and the plans are selected according to the score function.  Is there something wrong or did I misunderstand the scoring technique of matsim in each iteration?

**Comment by Janekdererste** [comment]
Hi, this repository is a fork of [matsim-exapmle-project](https://github.com/matsim-org/matsim-example-project), which is the right place for your question. 

I used this repository as part of the 2022 matsim class. 

As for your question: We don't write all files at every iteration, as writing to disk takes time. and increases the size of the output folder. You can set the writing intervalls in the `controler` section of the config file.

**Comment by BarshaLamichhane** [comment]
> Hi, this repository is a fork of [matsim-exapmle-project](https://github.com/matsim-org/matsim-example-project), which is the right place for your question.
> 
> I used this repository as part of the 2022 matsim class.
> 
> As for your question: We don't write all files at every iteration, as writing to disk takes time. and increases the size of the output folder. You can set the writing intervalls in the `controler` section of the config file.

Thank you for your reply @Janekdererste :)
